server:
  port: 9999

spring:
  redis:
    host: redis
    port: 6379
    database: 1

security:
  oauth2:
    client:
      client-id: auth_demo
      client-secret: 123456
      scope: all
    resource:
      loadBalanced: true
      token-info-uri: http://localhost:9998/oauth/check_token

